- include_tasks: dependencies.yml

- name: Install Zsh.
  package:
    name: zsh
    state: present
  become: yes

- name: Set Zsh as default shell
  become: yes
  command: chsh -s /bin/zsh {{ lookup('env' 'USER') }}
  register: zsh_for_user
  failed_when: zsh_for_user.rc >= 1
  changed_when: zsh_for_user.rc == 0

- name: Install Zsh configs.
  file:
    src: "{{ dotfiles_repo_local }}/zsh"
    path: "{{ config_path }}/zsh"
    state: link
    follow: false
    force: yes

- name: Link .zshenv file.
  file:
    src: "{{ dotfiles_repo_local }}/zsh/.zshenv"
    path: "~/.zshenv"
    state: link
    follow: false
    force: yes
