- name: Install Git.
  package:
    name: git
    state: present
  become: yes

- name: Install Git configs.
  file:
    src: "{{ dotfiles_repo_local }}/git"
    path: "{{ config_path }}/git"
    state: link
    follow: false
    force: yes
