- name: Install Zathura.
  package:
    name: zathura-pdf-mupdf
    state: present
  become: yes

- name: Install Zathura configs.
  file:
    src: "{{ dotfiles_repo_local }}/zathura"
    path: "{{ config_path }}/zathura"
    state: link
    follow: false
    force: yes
