- name: Install dunst.
  package:
    name: dunst
    state: present
  become: yes

- name: Install dunst configs.
  file:
    src: "{{ dotfiles_repo_local }}/i3-xorg/dunst"
    path: "{{ config_path }}/dunst"
    state: link
    follow: false
    force: yes
