- include_tasks: dependencies.yml

- name: Install Neovim.
  package:
    name: neovim
    state: present
  become: yes

- name: Install Neovim configs.
  file:
    src: "{{ dotfiles_repo_local }}/nvim"
    path: "{{ config_path }}/nvim"
    state: link
    follow: false
    force: yes
